# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ML4Cryo
tagline: Machine learning for the cryosphere
email: ml4cryo@gmail.com
twitter_username: ml4cryo
github_username:  ml4cryo
description: Machine learning for the Cryosphere (ML4cryo) is a research community focused on the intersection of machine learning and the cryospheric sciences. Our aim is to facilitate the integration of both communities, to steward impactful collaboration and thereby advance science.
author: Kim Bente and Julia Kaltenborn
url: https://github.com/ml4cryo
logo: /assets/images/favicon.png

# Reading Files
include:
  - _pages

# Collections
collections:
  news:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  fieldwork:
    output: true
    permalink: /:collection/:path/
  volunteering:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "page"


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
